## -*- docker-image-name: DOCKER_IMAGE_NAME -*-
#____________________________________________________________________
# File: Dockerfile.rb
#____________________________________________________________________
#
# Author: Shaun Ashby <shaun@ashby.ch>
# Created:
# Revision: $Id$
# Description:
#
# Copyright (C) 2014 Shaun Ashby
#
#
#--------------------------------------------------------------------
FROM xx:xx

MAINTAINER shaun.ashby@gmail.com

RUN xx

# End with a command to be run inside the container:
CMD ["XX","XX"]
