# -*- mode: ruby -*-
# vi: set ft=ruby :
#____________________________________________________________________
# File: Vagrantfile
#____________________________________________________________________
#
# Author: Shaun Ashby <shaun@ashby.ch>
# Created:
# Revision: $Id$
# Description: <desc here>
#
# Copyright (C) 2014 Shaun Ashby
#
#
#--------------------------------------------------------------------

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
VAGRANT_PROVIDER=docker

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider VAGRANT_PROVIDER do |d|
    d.build_dir = "."
    d.vagrant_machine = "<image name>"
  end
end
